%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    home/testLogPath
%    Worksheet: Sheet1
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/04/30 12:25:40

%Define testlog path
homeDirectory=pwd;
testLogPath=[homeDirectory,'/testLog'];
%% Import the data
%[~, ~, raw0_0] = xlsread('C:\Users\Tim\Desktop\Cooling_DATA\Optimass6400Research\TymMatlab2\OptimassMatlab\testlog.xlsx','Sheet1','A8:A8');
[~, ~, raw0_0] = xlsread(testLogPath,'Sheet1','A8:A8');
%[~, ~, raw0_1] = xlsread('C:\Users\Tim\Desktop\Cooling_DATA\Optimass6400Research\TymMatlab2\OptimassMatlab\testlog.xlsx','Sheet1','E8:F8');
[~, ~, raw0_1] = xlsread(testLogPath,'Sheet1','E8:F8');
%[~, ~, raw1_0] = xlsread('C:\Users\Tim\Desktop\Cooling_DATA\Optimass6400Research\TymMatlab2\OptimassMatlab\testlog.xlsx','Sheet1','A10:A45');
[~, ~, raw1_0] = xlsread(testLogPath,'Sheet1','A10:A45');
%[~, ~, raw1_1] = xlsread('C:\Users\Tim\Desktop\Cooling_DATA\Optimass6400Research\TymMatlab2\OptimassMatlab\testlog.xlsx','Sheet1','E10:F45');
[~, ~, raw1_1] = xlsread(testLogPath,'Sheet1','E10:F45');
raw = [raw0_0,raw0_1;raw1_0,raw1_1;];

%% Create output variable
data = cell2mat(raw);

%% Allocate imported array to column variable names
Test = data(:,1);
Temp = data(:,2);
Flow = data(:,3);

%% Clear temporary variables
clearvars data raw raw0_0 raw0_1 raw1_0 raw1_1 columnIndices;