%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Tim\Desktop\CERNmatlab\BartMatlab2\timestamps.xlsx
%    Worksheet: Sheet1
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/04/19 21:29:10

%% Import the data, extracting spreadsheet dates in MATLAB datenum format
%[~, ~, raw, dateNums] = xlsread('C:\Users\Tim\Desktop\Cooling_DATA\Optimass6400Research\TymMatlab2\OptimassMatlab\timestamps.xlsx','Sheet1','','',@convertSpreadsheetDates);
[~, ~, raw, dateNums] = xlsread(timestampsPath,'Sheet1','','',@convertSpreadsheetDates);
raw = raw(2:end,:);
dateNums = dateNums(2:end,:);

%% Replace date strings by MATLAB datenums
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find Excel dates
raw(R) = dateNums(R);

%% Replace non-numeric cells with 0.0
R = cellfun(@(x) ~isnumeric(x) || isnan(x),raw); % Find non-numeric cells
raw(R) = {0.0}; % Replace non-numeric cells

%% Create output variable
data = cell2mat(raw);

%% Allocate imported array to column variable names
ssDates = data(:,1);
ssTimes = data(:,2);
Test = data(:,3);
Temp = data(:,4);
Flow = data(:,5);

%% Clear temporary variables
clearvars data raw dateNums R columnIndices;